### PR TITLE
feat: Update pluginOptionsSchema with deprecation warnings

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Thanks to @mxstbr for creating https://github.com/gatsbyjs/gatsby/pull/27541 and pointing this out! 👊

### CODE REVIEW

**Comment by robinmetral** [comment]
@MichaelDeBoey the pipeline is timing out on a prompt from codecov, do you know what's happening?
https://travis-ci.org/github/robinmetral/gatsby-plugin-pinterest/jobs/738019770

**Comment by MichaelDeBoey** [comment]
@robinmetral I don't know what happened there tbh...

**Comment by robinmetral** [comment]
@MichaelDeBoey since the CI kept failing I disabled the node@latest job. Could you rebase this PR to get the new Travis config? I'll merge when status checks pass 🙂

**Comment by MichaelDeBoey** [comment]
@robinmetral Rebased my branch onto `upstream/master` 🙂

**Pull request merged**
