### PR TITLE
chore: Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Just like in #6, you'll need to checkout this branch and run `npx semantic-release-cli setup` to set the `NPM_TOKEN` secret for GitHub Actions

### CODE REVIEW

**Comment by robinmetral** [comment]
This looks great @MichaelDeBoey 🎉 Not a fan of Travis lately, there were a lot of delays for OSS builds.

Can you share a bit on the reasons why you thought we should switch? Is it because of those delays?

**Comment by MichaelDeBoey** [comment]
@robinmetral I already wanted to switch some time ago, but never had the time to look into it.
Now that @kentcdodds did the switch in [`generator-kcd-oss`](https://github.com/kentcdodds/generator-kcd-oss), I looked into it and did it for [`kcd-scripts`](https://github.com/kentcdodds/kcd-scripts) and a couple other of Kent's packages, so I wanted to do it here too.

**Comment by robinmetral** [comment]
Thanks for he background 🙂  Will set up the token tomorrow and merge this

**Comment by robinmetral** [comment]
Glad to see the CI is fixed on node@latest 🎉  and the runs are so fast 😍

**Pull request merged**
